#!/bin/zsh

get_source()
{
    mkdir $srcdir

    cd $srcdir

    snarf http://sysoev.ru/nginx/nginx-$version.tar.gz

    $sudo apt-get source nginx   
}

unpack_source()
{
    cd $srcdir/*(/)
    
    uupdate --upstream-version $version ../nginx-$version.tar.gz    
}

build_source()
{
    cd $srcdir/nginx-$version
    
    debuild -i -us -uc
}

install_deb()
{
    cd $srcdir

    $sudo dpkg -i nginx_$version*.deb && sudo aptitude hold nginx
}

cleanup()
{
    $sudo rm -Rf $srcdir
}

help()
{
    print "$me:t action"
    print " actions:"
    for a in $my_actions; do
	print "\t$a"
    done
}

me=$0
my_actions=( $(grep "()" $me | tr -d "()" | egrep -v "(help|grep)") )
[ -z $1 ] && help && exit 1

[ "$UID" = 0 ] || sudo=sudo

version=$1
srcdir=$HOME/src/nginx-$(date +%Y%m%d)

shift

if [ "$*" ]; then
    while  [ -n "$*" ]; do
	$1
	shift
    done
else
    for a in $my_actions; do
	$a
    done
fi