#!/bin/zsh

version=$1
srcdir=$HOME/src/nginx-$RANDOM

[ -z $1 ] && exit 127

[ "$UID" = 0 ] || sudo=sudo

mkdir $srcdir

cd $srcdir

snarf http://sysoev.ru/nginx/nginx-$version.tar.gz

$sudo apt-get source nginx

cd *(/)

uupdate --upstream-version $version ../nginx-$version.tar.gz

cd ../nginx-$version

debuild -i -us -uc

cd ../

$sudo dpkg -i nginx_$version*.deb && sudo aptitude hold nginx

$sudo killall -HUP nginx

$sudo rm -Rf $srcdir
