#!/bin/sh

echo -e "  \033[44m\033[1;37mcolor              code \033[0m"

echo -e "  \033[47;30mblack\033[0m              \033[47;30m0;30m\033[0m"
echo -e "\033[1;30m  black bold         1;30m"

echo -e "\033[0;31m  red                0;31m"
echo -e "\033[1;31m  red bold           1;31m"

echo -e "\033[0;32m  green              0;32m"
echo -e "\033[1;32m  green bold         1;32m"

echo -e "\033[0;33m  yellow             0;33m"
echo -e "\033[1;33m  yellow bold        1;33m"

echo -e "\033[0;34m  blue               0;34m"
echo -e "\033[1;34m  blue bold          1;34m"

echo -e "\033[0;35m  magenta            0;35m"
echo -e "\033[1;35m  magenta bold       1;35m"

echo -e "\033[0;36m  cyan               0;36m"
echo -e "\033[1;36m  cyan bold          1;36m"

echo -e "\033[0;37m  white              0;37m"
echo -e "\033[1;37m  white bold         1;37m \033[0m"

