#!/bin/zsh

#. /etc/colordefs

black="\033[0;30m"
BLACK="\033[1;30m"
red="\033[0;31m"
RED="\033[1;31m"
green="\033[0;32m"
GREEN="\033[1;32m"
yellow="\033[0;33m"
YELLOW="\033[1;33m"
blue="\033[0;34m"
BLUE="\033[1;34m"
magenta="\033[0;35m"
MAGENTA="\033[1;35m"
cyan="\033[0;36m"
CYAN="\033[1;36m"
white="\033[0;37m"
WHITE="\033[1;37m"
off="\033[0m"

parse_ipt_log()
{
	c=$2
	set -- $(print $1:gs/=/\ /)
	buf=( $buf "$blue$1=$c$2" )
}

parse_daemon()
{
	case $1 in
		*'['*']':)
			d=$(echo "$1" |  cut -d'[' -f1)
			p=$(echo "$1" |  cut -d'[' -f2 | tr -d ']:')
			print "$green$d$GREEN\[$WHITE$p$GREEN\]$off:"
			;;
		*)
			print "$green$1 "
	esac
}



parse_syslog()
{
	date="$CYAN$1 $2 $3"
	host=$YELLOW$4
	daemon=$(parse_daemon $5)
	
	shift 5

	buf=( $pref$date $host $daemon )

	line_color=$cyan	
	while [ -n "$*" ]; do
		case $1 in

		[0-9]*.[0-9]*.[0-9]*.[0-9]*)
			buf=( $buf $BLUE$1 )	;;
			
		[a-zA-Z0-9]*@[a-zA-Z0-9]*.*|'<'[a-zA-Z0-9]*@[a-zA-Z0-9]*.*'>'*)
			buf=( $buf $blue$1 )	;;
			
		IN=*|SRC=*|SPT=*)
			parse_ipt_log $1 $red	;;
		OUT=*|DST=*|DPT=*)
			parse_ipt_log $1 $RED	;;
		MAC=*|TOS=*|TTL=*|ID=*|LEN=*|PREC=*|WINDOW=*|RES=*|URGP=*)
			parse_ipt_log $1 $yellow;;
		PROTO=*)
			parse_ipt_log $1 $CYAN	;;
		SYN)
			buf=( $buf $CYAN$1 )	;;
		
		status)
			buf=( $buf $yellow$1 ) ;;
			
		login|starting|Freeing|Detected|starting|[aA]ccepted|[aA]uthenticated|Ready|active|[rR]eloading|saved|restarting|ONLINE)
			buf=( $buf $GREEN$1 )	;;
		dangling|closed|Assuming|root|root|exiting|missing|Ignored|adminalert:|deleting|OFFLINE)
			buf=( $buf $YELLOW$1 )	;;
		LOGIN|DHCP_OFFER|optimized|reset:|unloaded|disconnected|connect|[sS]uccess*|registered)
			buf=( $buf $MAGENTA$1 )	;;
		deny|DENY|lost|shutting|dead|DHCP_NAK|failure|Unable|inactive|terminating|refused|rejected|down|OFFLINE|*error*|ERROR*|failed:|fatal)
			buf=( $buf $RED$1 ); line_color=$red ;;
		warning:|WARNING:|invalid|obsolete|bad|Password|detected|timeout|wrong|Lame|FAILED|failing|unknown|obsolete|stopped|terminating|disabled|Lost)
			buf=( $buf $RED$1 ); line_color=$magenta	;;
		*)
			buf=( $buf $line_color$1 )
		esac
		shift
	done
	print "$buf$off"
}

parse_apache_log()
{
	QQ=$BLACK\"
	host=$(dnsname $1)
	ip=$1
	dashes="$off$2 $3"
	date="$YELLOW\[$CYAN$4:gs/[// $5:gs/]//$YELLOW\]"
	get=$green$6:gs/\"//
	file=$cyan$7
	ver=$green$8:gs/\"//
	shift 8
	codes="$MAGENTA$1 $2"
	ref=$red$3:gs/\"//
	shift 3
	agent="$magenta$*:gs/\"//"
	print "$BLUE${host:-$ip} $dashes $date $QQ$get $file $ver$QQ $codes $QQ$ref$QQ $QQ$agent_QQ"
	continue
}

cat /dev/stdin | while read line; do
	set -- $(echo $line)
	
	case $1 in
		'==>')	print "\n$WHITE$1 $off$2 $WHITE$3$off" 	;;
		[0-9]*.[0-9]*.[0-9]*.[0-9]*)
			parse_apache_log $@
		;; 
		*.*)	pref=( "$1 " ); shift
			parse_syslog $@
		;;
		*) 	[ "$*" ] && parse_syslog $*
	esac
done
